# Generated by Django 4.0.5 on 2022-07-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_draft",
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set and Is Published is True, the post will be available after the given value.",
                null=True,
            ),
        ),
    ]
