# Generated by Django 4.0.5 on 2022-07-10 17:16

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_remove_post_is_draft_post_is_published_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="summary",
            field=martor.models.MartorField(default=True),
            preserve_default=False,
        ),
    ]
