# Generated by Django 4.0.5 on 2022-08-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0006_alter_category_options_alter_subscription_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionnotification",
            options={},
        ),
        migrations.AddField(
            model_name="post",
            name="notifications_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, all notifications are considered to have been sent and will not be sent again.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionnotification",
            constraint=models.UniqueConstraint(
                fields=("post", "subscription"), name="subscript_notif_uniq"
            ),
        ),
    ]
