# Generated by Django 4.0.5 on 2022-08-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0008_alter_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="open_graph_description",
            field=models.TextField(
                blank=True, help_text="Used for SEO purposes and social media sharing."
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="open_graph_image",
            field=models.ImageField(
                blank=True,
                help_text="Used for SEO purposes and social media sharing.",
                null=True,
                upload_to="open_graph/",
            ),
        ),
    ]
