# Generated by Django 4.0.5 on 2022-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0009_post_open_graph_description_post_open_graph_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionnotification",
            name="read",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
