# Generated by Django 4.0.5 on 2022-09-10 15:56

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0010_subscriptionnotification_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="category_unq_slug",
        ),
        migrations.RemoveConstraint(
            model_name="post",
            name="post_unq_slug",
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                help_text="Unique URL-friendly identifier.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w]+\\Z"),
                        "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(
                help_text="Unique URL-friendly identifier.",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-\\w]+\\Z"),
                        "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
