name: Test

on:
  push:
    branches:
    - main
    - lab-1.1
    - lab-1.2
    - lab-1.3
    - lab-2.1
    - lab-2.2
    - lab-2.3
    - lab-2.4
  pull_request:

jobs:
  tests:
    name: Tests Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    env:
      SECRET_KEY: very-unstrustworthy

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m manage test

      - name: Run lab tests
        run: |
          python -m manage test --tag lab_test
